#ifndef __ERRORS_H
#define __ERRORS_H

const char* GetErrorString(int err);

enum Errors {
	ERROR_NONE = 0,

	ERROR_BUFFER_TOO_SMALL = -1,
	ERROR_FILE_IS_NOT_FOUND = -2,

	SOCKERR_SOCKET_FAILED = -51,  
	SOCKERR_WSASTARTUP_FAILED = -52,
	SOCKERR_UNABLE_TO_RESOLVE_HOSTNAME = -53,
	SOCKERR_UNABLE_TO_USE_HOSTNAME = -54,
	SOCKERR_CONNECT_FAILED = -55,
	SOCKERR_UNABLE_TO_INITIALIZE_SSL = -56,
	SOCKERR_SEND_ERROR = -57,
	SOCKERR_RECEIVE_ERROR = -58,
	SOCKERR_SSL_ERROR = -59,
	SOCKERR_SSL_CERTIFICATE_EXPIRED = -60,
	SOCKERR_SSL_CERTIFICATE_VERIFICATION = -61,
	SOCKERR_SSL_SEND_ERROR = -62,
	SOCKERR_SSL_RECEIVE_ERROR = -63,



	KEYERR_NAME_NOT_SET = -100,
	KEYERR_FAILED_TO_IMPORT_KEY = -101,
	KEYERR_FAILED_TO_LOAD_KEY = -102,
	KEYERR_FAILED_TO_SAVE_KEY = -103,
	KEYERR_INIT_FAILED = -104,
	KEYERR_INIT_EX_FAILED = -105,
	KEYERR_INVALID_KEY_TYPE = -106,
	KEYERR_SIGN_FAILED = -107,

	KEYERR_COMPUTE_FAILED = -108,

	SIGNERR_GENERAL_FAILURE = -150,
	SIGNERR_VERIFY_FAILURE = -151,

	VERIFYERR_GENERAL_FAILURE = -160,
	VERIFYERR_SIGNATURE_TOO_LARGE = -161,

	COMPUTEERR_GENERAL_FAILURE = -180,

	HTTP_ALREADY_EXECUTED = -200,
	HTTP_INVALID_URL = -201,
	HTTP_CANCELED_BY_USER = -202,

	CIPHER_FAILED_TO_INITIALIZE = -300,
	CIPHER_FAILED_TO_CRYPT = -301,

	KEY_FAILED_TO_CALCULATE_X3DH = -350,

	TRANSFER_INVALID_MESSAGE_CONTENTS = -500,
	TRANSFER_MESSAGE_EMPTY = -501,


	MEMERR_OUT_OF_MEMORY = -1000,


};


#endif